### ISSUE TITLE
Debugging issues with experiments/baoab_vs_vvvr.py

### ISSUE THREAD

**Issue by jchodera** [choderalab/integrator-benchmark#2]
@maxentile : I'm trying to dig into what might be going on with negative estimates of $\Delta F_{neq}$, but after installing the `integrator-benchmark` package via
```bash
python setup.py develop
```
there seems to be some issue with importing `benchmark.testsystems`:
```bash
lski1962:experiments choderaj$ python baoab_vs_vvvr.py 
Traceback (most recent call last):
  File "baoab_vs_vvvr.py", line 1, in <module>
    import benchmark.testsystems
  File "/Users/choderaj/github/choderalab/integrator-benchmark/integrator-benchmark/benchmark/experiments/benchmark.py", line 5, in <module>
    from code.integrators import LangevinSplittingIntegrator
ImportError: No module named 'code.integrators'; 'code' is not a package
```
My guess is
* There is some code that hasn't been checked in. `master` was last updated 24 days ago (!!!)
* You might have some old code installed locally as `code.integrators` that makes this work locally for you
* You are using a branch other than `master`. Could this be `refactor` (updated 19 days ago)?

Any idea what the issue might be?

**Comment by jchodera** [comment]
The same problem persists if I use the `refactor` branch:
```bash
lski1962:experiments choderaj$ python baoab_vs_vvvr.py 
Traceback (most recent call last):
  File "baoab_vs_vvvr.py", line 1, in <module>
    import benchmark.testsystems
  File "/Users/choderaj/github/choderalab/integrator-benchmark/integrator-benchmark/benchmark/experiments/benchmark.py", line 5, in <module>
    from code.integrators import LangevinSplittingIntegrator
ImportError: No module named 'code.integrators'; 'code' is not a package
```

**Comment by jchodera** [comment]
I realize it's also possible that the `baoab_vs_vvvr.py` example you pointed us to was run *before* the refactor.

**Comment by jchodera** [comment]
Aha! I think this is due to the use of relative imports, which only work in python 2.x; we need to switch to absolute imports for python 3.x.

The big question is whether I should do this for the `master` or `refactor` branch.

**Comment by jchodera** [comment]
Whoops, that is just one problem, it seems. I still can't find a `code` module.

**Comment by jchodera** [comment]
Hm, this is proving tricky since `benchmark` is both the name of the package and a submodule inside of `benchmark.experiments`.

**Comment by jchodera** [comment]
I think I've fixed this in #3.
